site_name: Python4Control
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Modern features
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  
  # Typography
  font:
    text: Roboto
    code: Roboto Mono
  
  # Icons
  icon:
    logo: material/sine-wave
    repo: fontawesome/brands/github
  favicon: assets/favicon.png

# Extra CSS for additional styling
extra_css:
  - assets/extra.css

# Navigation structure
nav:
  - Home: index.md
  - Course:
    - Introduction: course1/01_intro.md
  - Tutorials:
    - Getting Started: tutorials/tutorial-0/index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

# Repository info
repo_name: Hmustf/python4control
repo_url: https://github.com/Hmustf/python4control

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hmustf/python4control
      name: Python4Control on GitHub
