site_name: Python4Control
site_url: https://Hmustf.github.io/python4control/
repo_url: https://github.com/Hmustf/python4control
repo_name: Hmustf/python4control

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Control System Design with Python:
    - Introduction: control-design/01_intro.md
    - Control Functions: control-design/02_control_func.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Hmustf/python4control

copyright: |
  &copy; 2024 <a href="https://github.com/Hmustf"  target="_blank" rel="noopener">Hmustf</a>

use_directory_urls: false

extra_css:
  - static/css/extra.css
