title: Python for Control Systems
description: A comprehensive collection of tutorials for control system analysis and design using Python
baseurl: "/python4control"
url: "https://hmustf.github.io"

# Theme settings
theme: jekyll-theme-primer
markdown: GFM

# Repository settings
repository: Hmustf/python4control
github:
  is_project_page: true
  repository_url: https://github.com/Hmustf/python4control 